/// Simplified Chinese translations, keyed by the English UI text.
enum LocalizedStrings {
    static let chinese: [String: String] = [
        // Wheel, menu and toasts
        "Hold ⇧ while dragging a file to convert it": "拖动文件时按住 ⇧ 即可转换格式",
        "Hold ⌥⇧ for tools": "按住 ⌥⇧ 打开工具轮盘",
        "Recent": "最近",
        "Welcome Guide…": "使用指南…",
        "Welcome Guide": "使用指南",
        "Settings…": "设置…",
        "Quit Kumquat": "退出 Kumquat",
        "Cancel": "取消",
        "Close": "关闭",
        "Click to show in Finder": "点击在访达中显示",
        "Saved next to the original": "已保存在原文件旁边",
        "Saved": "已保存",
        "failed": "个失败",
        "Couldn't finish": "未能完成",
        "Couldn't save": "保存失败",
        "Nothing was saved.": "没有保存任何文件。",
        "Compressing": "正在压缩",
        "Rotating": "正在旋转",
        "Splitting pages": "正在拆分页面",
        "Merging": "正在合并",
        "Removing audio": "正在移除音轨",
        "Saving a frame": "正在截取画面",
        "Removing metadata": "正在清除元数据",
        "Working": "正在处理",

        // Shared tool window controls
        "Reset": "重置",
        "Apply": "应用",
        "Save": "保存",
        "Clear": "清除",
        "Undo": "撤销",
        "Auto": "自动",
        "Free": "自由",
        "Ratio": "比例",
        "Size": "大小",

        // Crop
        "Crop Image": "裁剪图片",
        "Aspect ratio": "宽高比",
        "Cropping image": "正在裁剪图片",
        "Cropped": "已裁剪",

        // Background
        "Add BG": "添加背景",
        "Background": "背景",
        "Padding": "边距",
        "Corners": "圆角",
        "Shadow": "阴影",
        "Save with Background": "保存带背景图片",
        "Use a picture as the background": "使用图片作为背景",
        "Choose a background picture": "选择背景图片",
        "Custom colour": "自定义颜色",
        "Adding background": "正在添加背景",
        "Background added": "背景已添加",

        // Edit
        "Edit Image": "编辑图片",
        "Original": "原图",
        "Hold to compare": "按住对比原图",
        "Rotate left": "向左旋转",
        "Rotate right": "向右旋转",
        "Flip horizontal": "水平翻转",
        "Flip vertical": "垂直翻转",
        "Exposure": "曝光",
        "Contrast": "对比度",
        "Saturation": "饱和度",
        "Vibrance": "自然饱和度",
        "Warmth": "色温",
        "Highlights": "高光",
        "Shadows": "阴影",
        "Sharpness": "锐度",
        "Vignette": "暗角",
        "Saving edits": "正在保存编辑",
        "Edits saved": "编辑已保存",

        // Annotate
        "Annotate": "标注",
        "Pen": "画笔",
        "Highlighter": "荧光笔",
        "Arrow": "箭头",
        "Rectangle": "矩形",
        "Ellipse": "椭圆",
        "Text": "文字",
        "Type text, then click the picture to place it": "输入文字，然后点击图片放置",
        "Saving annotations": "正在保存标注",
        "Annotations saved": "标注已保存",

        // Redact
        "Redact": "打码",
        "Black Box": "黑框",
        "Pixelate": "马赛克",
        "Blur": "模糊",
        "Find Text": "识别文字",
        "Find Faces": "识别人脸",
        "Nothing found.": "没有找到。",
        "Drag over anything you want to hide.": "拖动框选需要遮挡的内容。",
        "Redacting": "正在打码",
        "Redacted copy saved": "打码副本已保存",

        // Metadata
        "Metadata": "元数据",
        "Contains location": "包含位置信息",
        "No location data": "无位置信息",
        "Show in Maps": "在地图中显示",
        "Remove Location": "移除位置",
        "Remove All Metadata": "移除全部元数据",
        "Clean copy saved": "已保存干净副本",
        "Image": "图像",
        "Camera": "相机",
        "Author": "作者",
        "Location": "位置",
        "Dimensions": "尺寸",
        "File size": "文件大小",
        "Format": "格式",
        "Resolution": "分辨率",
        "Color model": "色彩模式",
        "Color profile": "色彩配置",
        "Bit depth": "位深度",
        "Orientation": "方向",
        "Make": "品牌",
        "Model": "型号",
        "Lens": "镜头",
        "Aperture": "光圈",
        "Shutter": "快门",
        "ISO": "ISO",
        "Focal length": "焦距",
        "Taken": "拍摄时间",
        "Software": "软件",
        "Artist": "作者",
        "Copyright": "版权",
        "Caption": "说明",
        "Keywords": "关键词",
        "Coordinates": "坐标",
        "Altitude": "海拔",

        // PDF info and watermark
        "PDF Info": "PDF 信息",
        "Title": "标题",
        "Subject": "主题",
        "Pages": "页数",
        "PDF version": "PDF 版本",
        "Created by": "创建程序",
        "Producer": "生成程序",
        "Created": "创建时间",
        "Modified": "修改时间",
        "Remove All": "全部移除",
        "Save Copy": "保存副本",
        "Saving PDF info": "正在保存 PDF 信息",
        "Watermark": "水印",
        "CONFIDENTIAL": "机密",
        "Opacity": "不透明度",
        "Angle": "角度",
        "Colour": "颜色",
        "Centre": "居中",
        "Tiled": "平铺",
        "Add Watermark": "添加水印",
        "Adding watermark": "正在添加水印",
        "Watermark added": "水印已添加",

        // Trim
        "Trim": "剪辑",
        "Drag the yellow handles, then click Trim.": "拖动黄色手柄，然后点击“剪辑”。",
        "Trimming": "正在剪辑",
        "Trimmed copy saved": "剪辑副本已保存",

        // Settings
        "Kumquat Settings": "Kumquat 设置",
        "Drag a file and hold ⇧ Shift": "拖动文件并按住 ⇧ Shift",
        "A wheel of formats appears around the pointer. Drop the file on one and the converted copy is saved next to the original.":
            "指针周围会出现格式轮盘。把文件拖放到某个格式上，转换后的副本会保存在原文件旁边。",
        "Hold ⌥ Option + ⇧ Shift for tools: compress, crop, add a background and more.":
            "按住 ⌥ Option + ⇧ Shift 打开工具：压缩、裁剪、添加背景等。",
        "Wheel size": "轮盘大小",
        "General": "通用",
        "Language": "语言",
        "System": "跟随系统",
        "Open at login": "登录时打开",
        "Play a sound when done": "完成时播放提示音",
        "Haptic feedback on trackpads": "触控板触感反馈",
        "Show results in Finder": "完成后在访达中显示",
        "Quality": "质量",
        "JPG / HEIC quality": "JPG / HEIC 质量",
        "Compress tool quality": "压缩工具质量",
        "PDF to image resolution": "PDF 转图片分辨率",
        "Lossless WebP": "无损 WebP",
        "Off: smaller lossy WebP files. Pictures with transparency are always saved losslessly.":
            "关闭时生成更小的有损 WebP；带透明通道的图片始终无损保存。",
        "Optional helpers": "可选辅助工具",
        "Use Homebrew tools when installed": "检测到 Homebrew 工具时使用",
        "MP3, WebM, MKV and other formats": "MP3、WebM、MKV 等格式",
        "Slightly smaller WebP": "体积稍小的 WebP",
        "Not installed": "未安装",
        "Copy": "拷贝",
        "Source on GitHub": "GitHub 源代码",

        // Welcome
        "Convert files right where they are — no windows, no uploads.": "就地转换文件——无需打开窗口，无需上传。",
        "Hold Shift while dragging": "拖动时按住 Shift",
        "Drop the file on a format. The converted copy is saved next to the original.":
            "把文件拖放到某个格式上，转换后的副本会保存在原文件旁边。",
        "Hold Option + Shift": "按住 Option + Shift",
        "Tools for the file type: compress, crop, add a background, redact and more.":
            "针对文件类型的工具：压缩、裁剪、添加背景、打码等。",
        "Try it now": "现在试试",
        "Start dragging the sample picture, press ⇧ Shift, then drop it on JPG or WEBP. Click the notification to see the result.":
            "拖动示例图片，按下 ⇧ Shift，然后把它放到 JPG 或 WEBP 上。点击提示即可查看结果。",
        "Kumquat lives in the menu bar. Everything stays on your Mac.": "Kumquat 常驻菜单栏，所有处理都在你的 Mac 本地完成。",
        "Get Started": "开始使用",
    ]
}
